name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Kód letöltése
      uses: actions/checkout@v3

    - name: .NET telepítése
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Függőségek visszaállítása
      run: dotnet restore PatientApi.sln

    - name: Megoldás buildelése
      run: dotnet build PatientApi.sln --no-restore --configuration Release

    - name: Tesztek futtatása
      run: dotnet test PatientApi.sln --no-build --verbosity normal
