name: Grant Temporary SQL Access

on:
  workflow_dispatch:

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
    - name: Kód letöltése
      uses: actions/checkout@v3

    - name: PowerShell szkript futtatása
      shell: pwsh
      run: ./AzureScript/Grant-TemporarySqlAccess.ps1
